GET http://localhost:4000/users

###

POST http://localhost:4000/users 
Content-Type: application/json

{
    "user": "dan",
    "password": "pickles"
    }
###

POST http://localhost:4000/login
Content-type: application/json

{
    "user": "dan",
    "password": "pickles"
}